# fly.toml app configuration file generated for ollava-bot on 2024-06-20T11:16:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = ''
primary_region = 'ord'

[env]
  LOG_LEVEL = 'INFO'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = 'data'
  destination = '/app/data'
  initial_size = '1gb'
